//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Acesso
{
	public virtual int ace_cod
	{
		get;
		set;
	}

	public virtual string ace_descricao
	{
		get;
		set;
	}

	public virtual Funcionario Funcionario
	{
		get;
		set;
	}

}

