//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Entrada
{
	public virtual int ent_cod
	{
		get;
		set;
	}

	public virtual int pro_cod
	{
		get;
		set;
	}

	public virtual int cod_barra
	{
		get;
		set;
	}

	public virtual Date ent_dt_fabricacao
	{
		get;
		set;
	}

	public virtual Date ent_dt_vencimento
	{
		get;
		set;
	}

	public virtual string ent_observacao
	{
		get;
		set;
	}

	public virtual Produto Produto
	{
		get;
		set;
	}

}

