//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Funcionario
{
	public virtual int fun_cod
	{
		get;
		set;
	}

	public virtual int ace_cod
	{
		get;
		set;
	}

	public virtual string fun_nome
	{
		get;
		set;
	}

	public virtual string fun_telefone
	{
		get;
		set;
	}

	public virtual string fun_login
	{
		get;
		set;
	}

	public virtual string fun_senha
	{
		get;
		set;
	}

	public virtual Venda Venda
	{
		get;
		set;
	}

}

