//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Pagamento
{
	public virtual int pag_cod
	{
		get;
		set;
	}

	public virtual string pag_descricao
	{
		get;
		set;
	}

}

