//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Produto
{
	public virtual int pro_cad
	{
		get;
		set;
	}

	public virtual int pro_cod_barra
	{
		get;
		set;
	}

	public virtual string pro_descricao
	{
		get;
		set;
	}

	public virtual int pro_prazo_validade
	{
		get;
		set;
	}

	public virtual int pro_uni_medida
	{
		get;
		set;
	}

	public virtual Double pro_peso_liquido
	{
		get;
		set;
	}

	public virtual Double pro_peso_bruto
	{
		get;
		set;
	}

	public virtual Double pro_estoque_mim
	{
		get;
		set;
	}

	public virtual string pro_estoque_max
	{
		get;
		set;
	}

	public virtual Float pro_preco_custo
	{
		get;
		set;
	}

	public virtual Float pro_preco_venda
	{
		get;
		set;
	}

	public virtual void produto()
	{
		throw new System.NotImplementedException();
	}

}

