//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Registro
{
	public virtual int res_cod
	{
		get;
		set;
	}

	public virtual int pro_cod
	{
		get;
		set;
	}

	public virtual int ent_cod
	{
		get;
		set;
	}

	public virtual int ven_cod
	{
		get;
		set;
	}

	public virtual Double res_quantidade
	{
		get;
		set;
	}

	public virtual string res_lote
	{
		get;
		set;
	}

	public virtual Date res_dt_operacao
	{
		get;
		set;
	}

	public virtual string res_tipo_operacao
	{
		get;
		set;
	}

	public virtual Entrada Entrada
	{
		get;
		set;
	}

	public virtual Venda Venda
	{
		get;
		set;
	}

}

