//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Venda
{
	private int ven_Cod
	{
		get;
		set;
	}

	public virtual int fun_cod
	{
		get;
		set;
	}

	public virtual int pag_cod
	{
		get;
		set;
	}

	public virtual Date ven_dt_venda
	{
		get;
		set;
	}

	public virtual Double ven_total
	{
		get;
		set;
	}

	public virtual Pagamento Pagamento
	{
		get;
		set;
	}

}

